const detailStudentsElements = {
    linkStudents: "//*[@id='root']//nav/a[contains(text(), 'Alunos')]",
    buttonAddStudent: "//*[@id='root']//button[contains(text(), 'Adicionar aluno')]",
    divAddStudent: "//*[@id='add_aluno']/div/h3[contains(text(), 'Incluir aluno')]",
    inputNameStudent: ".content_panel > #add_aluno > .modal_content > .form_modal > :nth-child(1) > :nth-child(1) > .form_control",
    inputRGStudent: "//*[@id='add_aluno']/div/form/div[1]/div[2]/div/input",
    inputCPFStudent: "//*[@id='add_aluno']/div/form/div[1]/div[3]/div/input",
    inputBirthStudent: "//*[@id='add_aluno']/div/form/div[1]/div[4]/div/input",
    inputCelStudent: "//*[@id='add_aluno']/div/form/div[1]/div[5]/div/input",
    selectTypeStudent: "//*[@id='add_aluno']//form/div[1]/div[6]//select",
    selectStatusStudent: "//*[@id='add_aluno']//form/div[1]/div[7]//select",
    selectSport: "//*[@id='add_aluno']//form/div[3]/div[1]//select",
    inputSchoolYear: ".content_panel > #add_aluno > .modal_content > .form_modal > :nth-child(3) > :nth-child(2) > .form_group > .form_control",
    selectPosition: "//*[@id='add_aluno']/div/form/div[4]/div/select",
    selectCT: "//*[@id='add_aluno']//form/div[5]//select",
    selectSkill: "//*[@id='add_aluno']//form/div[6]/div[1]//select",
    selectSublevel: "//*[@id='add_aluno']//form/div[6]/div[2]//select",
    inputEmail: "//*[@id='add_aluno']//form/div[7]/div[1]/input",
    selectMeetSchool: "//*[@id='add_aluno']//form/div[7]/div[2]/select",
    selectLaterality: "//*[@id='add_aluno']//form/div[7]/div[3]//select",
    labelTrainingSchedule: "//*[@id='add_aluno']//form/div[7]/div[4]//label[contains(.,'Horário de treino')]",
    selectTrainingSchedule: "//*[contains(@value,'MANHA')]",
    inputDueDate: "//*[@id='add_aluno']//form/div[7]/div[5]/input",
    labelStudentCode: "//*[@id='add_aluno']//form/div[7]/div[6]/label[contains(.,'Código do Aluno')]",
    inputStudentCode: "//*[@id='add_aluno']/div/form/div[7]/div[6]/input",
    labelBiologicSex: "//*[@id='add_aluno']//form/div[8]/div[1]//label[contains(.,'Sexo biológico')]",
    selectBiologicSex: "//*[@id='add_aluno']//form/div[8]/div[1]//select",
    labelCEP: "//*[@id='add_aluno']//form/div[8]/div[3]//label[contains(.,'CEP')]",
    inputCEP: "//*[@id='add_aluno']//form/div[8]/div[3]//input",
    labelMotherName: "//*[@id='add_aluno']//form/div[9]//label[contains(.,'Nome da mãe')]",
    inputMotherName: "//*[@id='add_aluno']/div/form/div[9]/div[1]/input",
    labelCPFMother: "//*[@id='add_aluno']/div/form/div[9]/div[2]/div/label[contains(.,'CPF da mãe')]",
    inputCPFMother: "//*[@id='add_aluno']/div/form/div[9]/div[2]/div/input",
    labelCelMother: "//*[@id='add_aluno']/div/form/div[9]/div[3]/div/label[contains(.,'Celular da mãe')]",
    inputCelMother: "//*[@id='add_aluno']/div/form/div[9]/div[3]/div/input",
    labelDaddyName: "//*[@id='add_aluno']//form/div[9]/div[4]/label[contains(.,'Nome do pai')]",
    inputDaddyName: "//*[@id='add_aluno']/div/form/div[9]/div[4]/input",
    labelCPFDaddy: "//*[@id='add_aluno']/div/form/div[9]/div[5]/div/label[contains(.,'CPF do pai')]",
    inputCPFDaddy: "//*[@id='add_aluno']/div/form/div[9]/div[5]/div/input",
    labelCelDaddy: "//*[@id='add_aluno']/div/form/div[9]/div[6]/div/label[contains(.,'Celular do pai')]",
    inputCelDaddy: "//*[@id='add_aluno']/div/form/div[9]/div[6]/div/input",
    labelNameFinancial: "//*[@id='add_aluno']/div/form/div[10]/div[1]/label[contains(.,'Nome Responsável Financeiro')]",
    inputNameFinancial: "//*[@id='add_aluno']/div/form/div[10]/div[1]/input",
    labelEmailFinancial: "//*[@id='add_aluno']/div/form/div[10]/div[2]/label[contains(.,'Email do responsável')]",
    inputEmailFinancial: "//*[@id='add_aluno']/div/form/div[10]/div[2]/input",
    labelRGFinancial: "//*[@id='add_aluno']/div/form/div[10]/div[3]/div/label[contains(.,'RG Responsável Financeiro')]",
    inputRGFinancial: "//*[@id='add_aluno']/div/form/div[10]/div[3]/div/input",
    labelCPFFinancial: "//*[@id='add_aluno']/div/form/div[10]/div[4]/div/label[contains(.,'CPF Responsável Financeiro')]",
    inputCPFFinancial: "//*[@id='add_aluno']/div/form/div[10]/div[4]/div/input",
    labelKinship: "//*[@id='add_aluno']/div/form/div[10]/div[5]/div/label[contains(.,'Parentesco')]",
    selectKinship: "//*[@id='add_aluno']/div/form/div[10]/div[5]/div/select",
    labelCelFinancial: "//*[@id='add_aluno']/div/form/div[10]/div[6]/div/label[contains(.,'Cel. Responsável Financeiro')]",
    inputCelFinancial: "//*[@id='add_aluno']/div/form/div[10]/div[6]/div/input",
    labelDescription: "//*[@id='add_aluno']/div/form/div[11]/label[contains(.,'Descrição')]",
    inputDescription: "//*[@id='add_aluno']/div/form/div[11]/textarea",
    divCardHeader: "//*[@id='root']/main/div[1]/div/div/main/div[1]/div[2]//h2[contains(.,'Procurar')]",
    labelSearchNameStudent: "//*[@id='root']/main/div[1]/div/div/main/div[1]/div[2]/form/div[1]/label[contains(.,'Nome')]",
    inputSearchNameStudent: "//*[@id='root']/main/div[1]/div/div/main/div[1]/div[2]/form/div[1]/input",
    buttonSearchStudent: "//*[@id='root']/main/div[1]/div/div/main/div[1]/div[2]/form/button[contains(.,'Buscar')]",
    divStudentSearch: "//*[@id='root']/main/div[1]/div/div/main/div[2]/div/div[1]/h2[contains(.,'Alunos')]",
    divContentCardStudent: "//*[@id='root']/main/div[1]/div/div/main/div[2]/div/div[2]/div/div[2]",
    divDetailsNameStudent: "//*[@id='root']/main/div[1]/div/div/main/div[2]/div/div[2]/div[1]/div[2]/div[1]/p",
    spanEditStudent: "//*[@id='root']/main/div[1]/div/div/main/div[2]/div/div[2]/div[1]/span[contains(.,'Editar aluno')]",
    buttonEditStudent: "//*[@id='add_aluno']/div/form/button[contains(.,'Alterar aluno')]",
    modalSucess: ".modal_content > .alert"
}

export default detailStudentsElements
